//! This module implements serde-based (de-)serialization for EBS block devices.
//!
//! Performs client-side validation of inputs (e.g. properly checks that invalid fields aren't
//! enabled based on volume type, or that requested volume sizes are within bounds.)
use aws_sdk_ec2::types::builders::EbsBlockDeviceBuilder;
use aws_sdk_ec2::types::{EbsBlockDevice as SdkEbsBlockDevice, VolumeType as SdkVolumeType};
use bon::Builder;
use bounded_integer::BoundedU64;
use num_traits::AsPrimitive;
use serde::{Deserialize, Serialize};
use serde_templated::TemplateOf;
use serde_templated::Templated;
use snafu::{OptionExt, Snafu};
use std::fmt::Debug;

/// The `EBSBlockDevice` type is generated by the following macro.
///
/// The macro takes, as input, the set of EBS volume types that are supported. The volume types are
/// defined like so:
///
/// ```ignore
/// impl_block_device_types! {
///     // Add addiitonal attributes to the device type as desired
///     $[derive(Default)]
///     Gp2 ("gp2") {
///         // Name of the `serde-templated` struct to generate
///         template: TemplatedGp2;
///
///         properties {
///             // Must start with a `volume_size` which is a (possibly-optional) BoundedU64
///             volume_size: Option<BoundedU64<MIN, MAX>>,
///             // Anything else goes below
///             iops: BoundedU64<MIN, MAX>,
///             something_else: String
///         }
///
///        // Instructions on how to build an AWS SDK volume using the type defined above
///        fn build(&self, builder) {
///            builder
///                .set_volume_size(self.volume_size.map(AsPrimitive::as_))
///                .iops(self.iops.as_())
///                .something_else(self.something_else.clone())
///        }
///     }
///
/// }
/// ```
///
/// By default, all EBS volume types defined this way will have the following properties added to
/// their struct definition:
///
/// ```ignore
/// pub delete_on_termination: Option<bool>,
/// pub encrypted: Option<bool>,
/// pub kms_key_id: Option<String>,
/// pub outpost_arn: Option<String>,
/// pub snapshot_id: Option<String>,
/// ```
///
/// This macro will generate the `EBSBlockDevice` enum which can be serde (de-)serialized,
/// which allows for any of the defined volume types to be read or written.
macro_rules! impl_block_device_types {
    ($(
        $(#[$struct_meta:meta])*
        $device:ident ($awsname:expr) {
            template: $templated_ty:ty;

            properties {
                volume_size: $size_ty:ty,
                $(
                    $(#[$extra_attr_meta:meta])*
                    $extra_attr:ident: $extra_ty:ty,
                )*
            }

            fn build(&$self:ident, $builder:ident) {
                $($impl_body:tt)+
            }
        }
    )*) => {
        #[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
        #[serde(rename_all = "kebab-case", tag = "volume-type")]
        pub enum EbsBlockDevice {
            $($device($device),)*
        }

        impl EbsBlockDevice {
            pub(crate) fn create_sdk_ebs_block_device(&self) -> SdkEbsBlockDevice {
                let builder = EbsBlockDeviceBuilder::default();
                match self {
                    $(Self::$device(device) => device
                            .configure_ebs_block_device(builder)
                            .volume_type(SdkVolumeType::$device),)*
                }
                .build()
            }

            pub fn as_ebs_device(&self) -> &dyn EbsBlockDeviceKind {
                match self {
                    $(Self::$device(device) => device,)*
                }
            }

            pub fn as_mut_ebs_device(&mut self) -> &mut dyn EbsBlockDeviceKind {
                match self {
                    $(Self::$device(device) => device,)*
                }
            }
        }

        /// Templated `EbsBlockDevice` type
        ///
        /// Implemented manually because the `Templated` macro does not support enums.
        #[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq)]
        #[serde(rename_all = "kebab-case", tag = "volume-type")]
        pub enum TemplatedEbsBlockDevice {
            $($device($templated_ty),)*
        }

        impl TemplateOf for TemplatedEbsBlockDevice {
            type Target = EbsBlockDevice;

            fn render(
                &self,
                template_context: &impl Serialize,
            ) -> Result<Self::Target, serde_templated::TemplatedError> {
                Ok(match self {
                    $(Self::$device(device) => {
                        EbsBlockDevice::$device(device.render(template_context)?)
                    },)*
                })
            }
        }

        // Implement each sub-device type
        $(
            #[derive(Debug, Clone, Serialize, Deserialize, Eq, PartialEq, Builder, Templated)]
            $(#[$struct_meta])*
            #[serde(deny_unknown_fields, rename_all = "kebab-case")]
            #[builder(on(_, into))]
            #[templated(
                derive(Debug, Clone, Eq, PartialEq, Builder),
                forward_attrs(serde, builder)
            )]
            pub struct $device {
                #[builder(with = |size: u64| -> Result<_, InvalidValueError> {
                    bounded_from_u64(size, $device::volume_type(), "volume-size")
                })]
                pub volume_size: $size_ty,
                $(
                    $(#[$extra_attr_meta])*
                    $extra_attr: $extra_ty,
                )*

                // Common EBS attributes
                pub delete_on_termination: Option<bool>,
                pub encrypted: Option<bool>,
                pub kms_key_id: Option<String>,
                pub outpost_arn: Option<String>,
                pub snapshot_id: Option<String>,
            }

            impl $device {
                fn configure_ebs_block_device(
                    &$self,
                    mut $builder: EbsBlockDeviceBuilder,
                ) -> EbsBlockDeviceBuilder {
                    $builder = $builder
                        .set_delete_on_termination($self.delete_on_termination)
                        .set_encrypted($self.encrypted)
                        .set_kms_key_id($self.kms_key_id.clone())
                        .set_outpost_arn($self.outpost_arn.clone())
                        .set_snapshot_id($self.snapshot_id.clone());
                    $($impl_body)*
                }

                pub fn volume_type() -> &'static str {
                    $awsname
                }
            }

            impl EbsBlockDeviceKind for $device {
                fn volume_type(&self) -> &'static str {
                    Self::volume_type()
                }

                fn volume_size(&self) -> Option<u64> {
                    self.volume_size.map(AsPrimitive::as_)
                }

                fn set_volume_size(&mut self, volume_size: Option<u64>) -> Result<(), InvalidValueError> {
                    if let Some(volume_size) = volume_size {
                        let volume_type = Self::volume_type();
                        self.volume_size = Some(bounded_from_u64(volume_size, volume_type, "volume-size")?);
                    }
                    Ok(())
                }

                fn delete_on_termination(&self) -> Option<bool> {
                    self.delete_on_termination
                }

                fn set_delete_on_termination(&mut self, delete_on_termination: Option<bool>) {
                    self.delete_on_termination = delete_on_termination;
                }

                fn encrypted(&self) -> Option<bool> {
                    self.encrypted
                }

                fn set_encrypted(&mut self, encrypted: Option<bool>) {
                    self.encrypted = encrypted;
                }

                fn kms_key_id(&self) -> Option<&str> {
                    self.kms_key_id.as_deref()
                }

                fn set_kms_key_id(&mut self, kms_key_id: Option<String>) {
                    self.kms_key_id = kms_key_id;
                }

                fn outpost_arn(&self) -> Option<&str> {
                    self.outpost_arn.as_deref()
                }

                fn set_outpost_arn(&mut self, outpost_arn: Option<String>) {
                    self.outpost_arn = outpost_arn;
                }

                fn snapshot_id(&self) -> Option<&str> {
                    self.snapshot_id.as_deref()
                }

                fn set_snapshot_id(&mut self, snapshot_id: Option<String>) {
                    self.snapshot_id = snapshot_id;
                }
            }

            impl From<$device> for EbsBlockDevice {
                fn from(value: $device) -> Self {
                    Self::$device(value)
                }
            }

            impl From<$templated_ty> for TemplatedEbsBlockDevice {
                fn from(value: $templated_ty) -> Self {
                    Self::$device(value)
                }
            }
        )*
    };
}

impl_block_device_types! {
    #[derive(Default)]
    Standard ("standard") {
        template: TemplatedStandard;

        properties {
            volume_size: Option<BoundedU64<1, 1_024>>,
        }

        fn build(&self, builder) {
            builder.set_volume_size(self.volume_size.map(AsPrimitive::as_))
        }
    }

    Io1 ("io1") {
        template: TemplatedIo1;

        properties {
            volume_size: Option<BoundedU64<4, 16_384>>,
            #[builder(with = |size: u64| -> Result<_, InvalidValueError> {
                bounded_from_u64(size, "io1", "iops")
            })]
            iops: BoundedU64<100, 64_000>,
        }

        fn build(&self, builder) {
            builder
                .set_volume_size(self.volume_size.map(AsPrimitive::as_))
                .iops(self.iops.as_())
        }
    }

    Io2 ("io2") {
        template: TemplatedIo2;

        properties {
            volume_size: Option<BoundedU64<4, 65_536>>,
            #[builder(with = |size: u64| -> Result<_, InvalidValueError> {
                bounded_from_u64(size, "io2", "iops")
            })]
            iops: BoundedU64<100, 256_000>,
        }

        fn build(&self, builder) {
            builder
                .set_volume_size(self.volume_size.map(AsPrimitive::as_))
                .iops(self.iops.as_())
        }
    }

    #[derive(Default)]
    Gp2 ("gp2") {
        template: TemplatedGp2;

        properties {
            volume_size: Option<BoundedU64<1, 16_384>>,
        }

        fn build(&self, builder) {
            builder.set_volume_size(self.volume_size.map(AsPrimitive::as_))
        }
    }

    #[derive(Default)]
    Sc1 ("sc1") {
        template: TemplatedSc1;

        properties {
            volume_size: Option<BoundedU64<125, 16_384>>,
        }

        fn build(&self, builder) {
            builder.set_volume_size(self.volume_size.map(AsPrimitive::as_))
        }
    }

    #[derive(Default)]
    St1 ("st1") {
        template: TemplatedSt1;

        properties {
            volume_size: Option<BoundedU64<125, 16_384>>,
        }

        fn build(&self, builder) {
            builder.set_volume_size(self.volume_size.map(AsPrimitive::as_))
        }
    }

    #[derive(Default)]
    Gp3 ("gp3") {
        template: TemplatedGp3;

        properties {
            volume_size: Option<BoundedU64<1, 16_384>>,
            #[builder(with = |size: u64| -> Result<_, InvalidValueError> {
                bounded_from_u64(size, "gp3", "iops")
            })]
            iops: Option<BoundedU64<3_000, 16_000>>,
            #[builder(with = |size: u64| -> Result<_, InvalidValueError> {
                bounded_from_u64(size, "gp3", "throughput")
            })]
            throughput: Option<BoundedU64<125, 1_000>>,
        }

        fn build(&self, builder) {
            builder
                .set_iops(self.iops.map(AsPrimitive::as_))
                .set_throughput(self.throughput.map(AsPrimitive::as_))
                .set_volume_size(self.volume_size.map(AsPrimitive::as_))
        }
    }
}

/// Abstracts over EBS volume types and allow fetching and setting of common keys.
pub trait EbsBlockDeviceKind {
    fn volume_type(&self) -> &str;

    fn volume_size(&self) -> Option<u64>;
    fn set_volume_size(&mut self, volume_size: Option<u64>) -> Result<(), InvalidValueError>;

    fn delete_on_termination(&self) -> Option<bool>;
    fn set_delete_on_termination(&mut self, delete_on_termination: Option<bool>);

    fn encrypted(&self) -> Option<bool>;
    fn set_encrypted(&mut self, encrypted: Option<bool>);

    fn kms_key_id(&self) -> Option<&str>;
    fn set_kms_key_id(&mut self, kms_key_id: Option<String>);

    fn outpost_arn(&self) -> Option<&str>;
    fn set_outpost_arn(&mut self, outpost_arn: Option<String>);

    fn snapshot_id(&self) -> Option<&str>;
    fn set_snapshot_id(&mut self, snapshot_id: Option<String>);
}

impl EbsBlockDeviceKind for EbsBlockDevice {
    fn volume_type(&self) -> &str {
        self.as_ebs_device().volume_type()
    }

    fn volume_size(&self) -> Option<u64> {
        self.as_ebs_device().volume_size()
    }

    fn delete_on_termination(&self) -> Option<bool> {
        self.as_ebs_device().delete_on_termination()
    }

    fn encrypted(&self) -> Option<bool> {
        self.as_ebs_device().encrypted()
    }

    fn kms_key_id(&self) -> Option<&str> {
        self.as_ebs_device().kms_key_id()
    }

    fn outpost_arn(&self) -> Option<&str> {
        self.as_ebs_device().outpost_arn()
    }

    fn snapshot_id(&self) -> Option<&str> {
        self.as_ebs_device().snapshot_id()
    }

    fn set_volume_size(&mut self, volume_size: Option<u64>) -> Result<(), InvalidValueError> {
        self.as_mut_ebs_device().set_volume_size(volume_size)
    }

    fn set_delete_on_termination(&mut self, delete_on_termination: Option<bool>) {
        self.as_mut_ebs_device()
            .set_delete_on_termination(delete_on_termination);
    }

    fn set_encrypted(&mut self, encrypted: Option<bool>) {
        self.as_mut_ebs_device().set_encrypted(encrypted);
    }

    fn set_kms_key_id(&mut self, kms_key_id: Option<String>) {
        self.as_mut_ebs_device().set_kms_key_id(kms_key_id);
    }

    fn set_outpost_arn(&mut self, outpost_arn: Option<String>) {
        self.as_mut_ebs_device().set_outpost_arn(outpost_arn);
    }

    fn set_snapshot_id(&mut self, snapshot_id: Option<String>) {
        self.as_mut_ebs_device().set_snapshot_id(snapshot_id);
    }
}

/// Creates a BoundedU64 from a u64, returning [`InvalidValueError`] if the input is out of bounds.
///
/// This is needed because [`TryFrom`] is not implemented by [`bounded_integer`].
fn bounded_from_u64<const MIN: u64, const MAX: u64>(
    value: u64,
    volume_type: &str,
    field: &str,
) -> Result<BoundedU64<MIN, MAX>, InvalidValueError> {
    BoundedU64::new(value).context(invalid_value_error::InvalidValueSnafu {
        min: MIN,
        max: MAX,
        field,
        volume_type,
        value,
    })
}

#[derive(Debug, Snafu)]
#[snafu(module)]
#[snafu(display(
    "Invalid value {value}' not within bounds [{min}, {max}] \
        for field '{field}' of volume-type '{volume_type}'"
))]
pub struct InvalidValueError {
    value: u64,
    min: u64,
    max: u64,
    field: String,
    volume_type: String,
}
