[workspace]
resolver = "2"

default-members = ["twoliter"]
members = [
    "tools/amispec",
    "tools/bottlerocket-variant",
    "tools/buildsys",
    "tools/buildsys-config",
    "tools/include-env-compressed",
    "tools/include-env-compressed/include-env-compressed-macro",
    "tools/oci-cli-wrapper",
    "tools/parse-datetime",
    "tools/pipesys",
    "tools/pubsys",
    "tools/pubsys-config",
    "tools/pubsys-setup",
    "tools/serde-templated",
    "tools/serde-templated-derive",
    "tools/testsys",
    "tools/testsys-config",
    "tools/unplug",
    "tools/update-metadata",

    "twoliter",
    "twoliter/src/tool-crates/*",

    "tests/integration-tests",
]

[profile.release]
strip = "debuginfo"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.1.0"
# CI backends to support (see 'cargo dist generate-ci')
ci = ["github"]
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]

[workspace.metadata.cross.build]
pre-build = [
    # install golang and patch for krane-bundle
    "apt update && apt --assume-yes install golang-1.22 patch",
    "update-alternatives --install /usr/bin/go go /usr/lib/go-1.22/bin/go 10",
    # give the builder access to the go build and module caches
    "mkdir /.cache && chmod a+rw /.cache",
    "mkdir /go && chmod a+rw /go",
]

[workspace.dependencies]
amispec = { version = "0.1", path = "tools/amispec" }
bottlerocket-types = { version = "0.0.16", git = "https://github.com/bottlerocket-os/bottlerocket-test-system", tag = "v0.0.16" }
bottlerocket-variant = { version = "0.1", path = "tools/bottlerocket-variant" }
buildsys = { version = "0.1", path = "tools/buildsys", lib = true, artifact = [ "bin:buildsys" ] }
buildsys-config = { version = "0.1", path = "tools/buildsys-config" }
include-env-compressed = { version = "0.1", path = "tools/include-env-compressed" }
include-env-compressed-macro = { version = "0.1", path = "tools/include-env-compressed/include-env-compressed-macro" }
krane-bundle = { version = "0.1", path = "tools/krane" }
oci-cli-wrapper = { version = "0.1", path = "tools/oci-cli-wrapper" }
parse-datetime = { version = "0.1", path = "tools/parse-datetime" }
path-absolutize = "3.1"
pipesys = { version = "0.1", path = "tools/pipesys", lib = true, artifact = [ "bin:pipesys" ] }
pubsys = { version = "0.1", path = "tools/pubsys", artifact = [ "bin:pubsys" ] }
pubsys-config = { version = "0.1", path = "tools/pubsys-config" }
pubsys-setup = { version = "0.1", path = "tools/pubsys-setup", artifact = [ "bin:pubsys-setup" ] }
serde-templated = { version = "0.1", path = "tools/serde-templated" }
serde-templated-derive = { version = "0.1", path = "tools/serde-templated-derive" }
testsys = { version = "0.1", path = "tools/testsys", artifact = [ "bin:testsys" ] }
testsys-config = { version = "0.1", path = "tools/testsys-config" }
testsys-model = { version = "0.0.16", git = "https://github.com/bottlerocket-os/bottlerocket-test-system", tag = "v0.0.16" }

twoliter = { version = "0.13.0-rc1", path = "twoliter", artifact = [ "bin:twoliter" ] }
twoliter-tool-buildsys = { version = "0.1", path = "twoliter/src/tool-crates/buildsys" }
twoliter-tool-embedded-bundle = { version = "0.1", path = "twoliter/src/tool-crates/embedded-bundle" }
twoliter-tool-pipesys = { version = "0.1", path = "twoliter/src/tool-crates/pipesys" }
twoliter-tool-pubsys = { version = "0.1", path = "twoliter/src/tool-crates/pubsys" }
twoliter-tool-pubsys-setup = { version = "0.1", path = "twoliter/src/tool-crates/pubsys-setup" }
twoliter-tool-testsys = { version = "0.1", path = "twoliter/src/tool-crates/testsys" }
twoliter-tool-tuftool = { version = "0.1", path = "twoliter/src/tool-crates/tuftool" }
twoliter-tool-unplug = { version = "0.1", path = "twoliter/src/tool-crates/unplug" }

unplug = { version = "0.1", path = "tools/unplug", artifact = [ "bin:unplug" ] }
update-metadata = { version = "0.1", path = "tools/update-metadata" }

anyhow = "1"
async-recursion = "1"
async-stream = "0.3"
async-trait = "0.1"
async-walkdir = "1"
aws-config = { version = "1", default-features = false, features = ["credentials-process", "default-https-client", "rt-tokio" ] }
aws-credential-types = "1"
aws-sdk-ebs = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-ec2 = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-kms = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-ssm = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-sdk-sts = { version = "1", default-features = false, features = ["default-https-client", "rt-tokio"] }
aws-smithy-types = "1"
aws-types = "1"
base64 = "0.22"
bon = "3"
bounded-integer = "0.5"
bytes = "1"
chrono = { version = "0.4", default-features = false }
clap = "4"
coldsnap = { version = "0.9", default-features = false }
daemonize = "0.5"
darling = "0.21"
duct = "1.1"
env_logger = "0.11"
fastrand = "2"
filetime = "0.2"
flate2 = "1"
futures = "0.3"
governor = "0.10"
guppy = "0.17"
handlebars = "6"
hex = "0.4"
home = "0.5"
indicatif = "0.18"
inotify = "0.11"
lazy_static = "1"
libc = "0.2"
log = "0.4"
lzma-rs = "0.3"
maplit = "1"
mockall = "0.13"
nix = "0.30"
nonzero_ext = "0.3"
num_cpus = "1"
num-traits = "0.2"
once_cell = "1.21"
olpc-cjson = "0.1"
proc-macro2 = "1"
quote = "1"
rand = { version = "0.9", default-features = false }
regex = "1"
reqwest = { version = "0.12", default-features = false }
seccompiler = "0.5"
semver = "1"
serde = "1"
serde_json = "1"
serde_plain = "1"
serde_yaml = "0.9"
sha2 = "0.10"
shell-words = "1"
simplelog = "0.12"
snafu = "0.8"
syn = "2"
strum = "0.27"
tabled = "0.15"
tar = "0.4"
tempfile = "3"
terminal_size = "0.4"
test-case = "3"
tinytemplate = "1"
tokio = "1"
tokio-stream = "0.1"
tokio-retry = "0.3"
toml = "0.9"
tough = "0.21"
tough-kms = "0.13"
tough-ssm = "0.16"
tracing = "0.1"
tuftool = { version = "0.14", artifact = [ "bin:tuftool" ] }
uds = "0.4"
unescape = "0.1"
url = "2"
uuid = "1"
walkdir = "2"
which = "8"
zstd = "0.13"

[profile.dev.package]
aws-config = { hint-mostly-unused = true }
aws-sdk-ebs = { hint-mostly-unused = true }
aws-sdk-ec2 = { hint-mostly-unused = true }
aws-sdk-kms = { hint-mostly-unused = true }
aws-sdk-ssm = { hint-mostly-unused = true }
aws-sdk-sts = { hint-mostly-unused = true }
aws-smithy-types = { hint-mostly-unused = true }
aws-types = { hint-mostly-unused = true }

[profile.release.package]
aws-config = { hint-mostly-unused = true }
aws-sdk-ebs = { hint-mostly-unused = true }
aws-sdk-ec2 = { hint-mostly-unused = true }
aws-sdk-kms = { hint-mostly-unused = true }
aws-sdk-ssm = { hint-mostly-unused = true }
aws-sdk-sts = { hint-mostly-unused = true }
aws-smithy-types = { hint-mostly-unused = true }
aws-types = { hint-mostly-unused = true }

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "fat"
codegen-units = 1

[workspace.lints.clippy]
disallowed-methods = "deny"
