[package]
name = "twoliter"
version = "0.11.0"
edition = "2021"
description = "A command line tool for creating custom builds of Bottlerocket"
authors = ["Matthew James Briggs <brigmatt@amazon.com>"]
repository = "https://github.com/bottlerocket-os/twoliter"
license = "MIT OR Apache-2.0"
keywords = ["twoliter", "bottlerocket"]
exclude = ["/design", "/target", "/dockerfiles", "/scripts"]

[dependencies]
anyhow.workspace = true
async-recursion.workspace = true
async-walkdir.workspace = true
async-trait.workspace = true
base64.workspace = true
buildsys-config.workspace = true
clap = { workspace = true, features = ["derive", "env", "std"] }
env_logger.workspace = true
filetime.workspace = true
flate2.workspace = true
futures.workspace = true
krane-bundle.workspace = true
lazy_static.workspace = true
log.workspace = true
oci-cli-wrapper.workspace = true
olpc-cjson.workspace = true
path-absolutize.workspace = true
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
strum = { workspace = true, features = ["derive"] }
tar.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["fs", "macros", "process", "rt-multi-thread"] }
toml.workspace = true
tracing = { workspace = true, features = ["log"] }
uuid = { workspace = true, features = ["v4"] }
which.workspace = true
zstd.workspace = true

# Binary dependencies. These are binaries that we want to embed in the Twoliter binary
twoliter-tool-buildsys.workspace = true
twoliter-tool-embedded-bundle.workspace = true
twoliter-tool-pipesys.workspace = true
twoliter-tool-pubsys.workspace = true
twoliter-tool-pubsys-setup.workspace = true
twoliter-tool-testsys.workspace = true
twoliter-tool-tuftool.workspace = true
twoliter-tool-unplug.workspace = true

[build-dependencies]
bytes.workspace = true
flate2.workspace = true
tar.workspace = true

[dev-dependencies]
test-case.workspace = true

[features]
default = ["integ-tests"]
integ-tests = []

[lints]
workspace = true
