[package]
name = "update_metadata"
version = "0.1.0"
authors = ["Samuel Mendoza-Jonas <samjonas@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
chrono = { version = "0.4.9", features = ["serde"] }
parse-datetime = { path = "../../parse-datetime" }
rand = "0.7.0"
regex = "1.1"
semver = { version = "0.9.0", features = ["serde"] }
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.40"
serde_plain = "0.3.0"
snafu = "0.6.0"
toml = "0.5"
tough = "0.7.1"

[lib]
name = "update_metadata"
path = "src/lib.rs"
