[package]
name = "eif-builder"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[dependencies]
aws-config.workspace = true
aws-lc-rs.workspace = true
aws-sdk-kms.workspace = true
aws-types.workspace = true
clap = { workspace = true, features = ["derive"] }
coset.workspace = true
crc32fast.workspace = true
error-utils.workspace = true
flate2.workspace = true
pem.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_cbor.workspace = true
serde_json.workspace = true
snafu.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
x509-cert.workspace = true
zstd.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
