[unstable]
bindeps = true
profile-hint-mostly-unused = true

[build]
# This is the recommended configuration that yields the
# best results:
#  - https://blog.rust-lang.org/2023/11/09/parallel-rustc.html
rustflags = ["-Z", "threads=8"]
