#!/usr/bin/env bash
#
# Create a kit from RPM package inputs.
set -eu -o pipefail

declare -a PACKAGES

for opt in "$@"; do
   optarg="$(expr "${opt}" : '[^=]*=\(.*\)')"
   case "${opt}" in
      --packages-dir=*) PACKAGES_DIR="${optarg}" ;;
      --package=*) PACKAGES+=("${optarg}") ;;
      --output-dir=*) OUTPUT_DIR="${optarg}" ;;
   esac
done

# HACK: because we're not passing KIT from buildsys
export KIT="${VARIANT}"

# FIXME: should this be a versioned directory?
# - needs to change whenever the kit changes?
# - needs to be predictable for publishing to work?
# - needs to avoid ambiguity if we have other local builds of the same kit?
KIT_DIR="${OUTPUT_DIR}/${ARCH}"

mkdir -p "${KIT_DIR}/Packages"
for pkg in ${PACKAGES} ; do
  find "${PACKAGES_DIR}/${pkg}" \
    -mindepth 1 \
    -maxdepth 1 \
    ! -name '*-debuginfo-*' \
    ! -name '*-debugsource-*' \
    -size +0c \
    -exec install -p -m 0644 -t "${KIT_DIR}/Packages" {} \+
done

createrepo_c "${KIT_DIR}"
dnf --disablerepo '*' --repofrompath "kit,file:///${KIT_DIR}" repoquery --all
