[package]
name = "pcrsys"
version = "0.1.0"
license = "Apache-2.0 OR MIT"
edition = "2021"
publish = false

[dependencies]
bon.workspace = true
nutype = { workspace = true, features = ["serde"] }
authenticode = { workspace = true, features = ["object"] }
aws-config.workspace = true
aws-sdk-ebs.workspace = true
aws-sdk-ec2.workspace = true
aws-types.workspace = true
base64.workspace = true
bit_field.workspace = true
clap = { workspace = true, features = ["derive"] }
coldsnap = { workspace = true, features = ["aws-sdk-rust-rustls"] }
crc32fast.workspace = true
ext4-view.workspace = true
fatfs.workspace = true
flate2 = { workspace = true, features = ["zlib"] }
gptman.workspace = true
hex.workspace = true
hex-literal.workspace = true
object.workspace = true
pest.workspace = true
pest_derive.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2.workspace = true
snafu.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
test-case.workspace = true
