name: Rust
on:
  # triggers when a PR is posted
  pull_request:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
      - "**.plantuml"
      - "**.svg"
jobs:
  build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - run: cargo install cargo-deny --locked
      - run: cargo install cargo-make --locked
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: "^1.18"
      # Install `patch`, needed to build `krane-bundle`, and tools for linking against musl
      - run: sudo apt-get install -y patch musl-tools musl-dev
      - run: rustup target add x86_64-unknown-linux-musl
      - run: CARGO_BUILD_TARGET=x86_64-unknown-linux-musl make build

  cross-build:
    runs-on:
      group: bottlerocket
      labels: bottlerocket_ubuntu-latest_16-core
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
          - target: aarch64-unknown-linux-musl
    env:
      TARGET_TRIPLE: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: mlugg/setup-zig@475c97be87a204e6c57fe851f970bd02005a70f0
        with:
          version: 0.14.1
      - name: Install ZigBuild
        # Pin cargo zigbuild to a version that we know is working for us.
        run: |
          cargo install cargo-zigbuild --locked --version 0.20.0
      - name: Rust stdlib
        run: |
          rustup target add "${TARGET_TRIPLE}"
      - run: |
          cargo zigbuild --release --bin twoliter --target "${TARGET_TRIPLE}"
